base_images:
  base:
    name: "4.17"
    namespace: ocp
    tag: ansible
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
build_root:
  project_image:
    dockerfile_literal: |-
      FROM registry.redhat.io/ubi9/python-312

      # Prow expects to be able to check out a repo under /go
      USER 0:0
      WORKDIR /go
      RUN chown 1001:0 .

      USER 1001:0

      RUN pip3 install --no-cache-dir ansible-lint
releases:
  latest:
    release:
      architecture: amd64
      channel: candidate
      version: "4.17"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: ansible-lint
  commands: |
    ansible-lint playbooks/
  container:
    from: src
  run_if_changed: playbooks/
zz_generated_metadata:
  branch: main
  org: openshift-kni
  repo: eco-ci-cd
  variant: lint
